# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import torch
import numpy as np
import matplotlib.pyplot as plt

# --- Device ---
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

# --- Load AR dataset ---
data = np.load('/content/ar_database_stacked_128x128.npz')
stack = data['stack']
X = stack / 255.0
X = X.reshape(X.shape[0], -1)  # flatten
X = torch.tensor(X, dtype=torch.float32, device=device)
n_samples, n_features = X.shape
print("Data loaded. Shape:", X.shape)

# --- Parameters ---
r = 50        # number of principal components
h = 100       # number of activated error terms
sigma = 1.0   # adaptive loss parameter
gamma = 1.0   # regularization for weights
max_iter = 10

# --- Step 0: Initialization ---
p = torch.ones(n_samples, device=device) / n_samples
b = torch.mean(X, dim=0)
W = torch.randn(n_features, r, device=device)
U_diag = torch.ones(n_samples, device=device)

print("Initialization complete:")
print(f"p shape: {p.shape}, sum(p): {p.sum().item()}")
print(f"b shape: {b.shape}")
print(f"W shape: {W.shape}")
print(f"U_diag shape: {U_diag.shape}")

# --- Main Iterative Loop ---
for iteration in range(max_iter):
    print(f"\n=== Iteration {iteration+1} ===")

    # --- Step 1: Update W ---
    print("Step 1: Updating W...")
    try:
        # weighted data for SVD
        X_weighted = X.T * torch.sqrt(U_diag)
        _, _, Vt = torch.linalg.svd(X_weighted.T, full_matrices=False)
        W = Vt.T[:, :r]
        print("W updated. Shape:", W.shape)
    except Exception as e:
        print("Error updating W:", e)

    # --- Step 2: Update b ---
    print("Step 2: Updating b...")
    b = (X.T @ U_diag) / U_diag.sum()
    print("b updated. Shape:", b.shape)
    print("Sample b values:", b[:5].cpu().numpy())

    # --- Step 3: Update U_diag (adaptive normalization) ---
    print("Step 3: Updating U_diag...")
    avg_local_dist = torch.sum((X - X.mean(dim=0))**2, dim=1) + sigma
    U_diag = n_samples * p * (1 + sigma) / avg_local_dist
    print("U_diag updated. Sample values:", U_diag[:10].cpu().numpy())

    # --- Step 4: Update weights p (top-h logic) ---
    print("Step 4: Updating weights p...")
    recon_error = torch.sum((X - (X @ W @ W.T + b))**2, dim=1)

    # Top-h threshold
    sorted_errors, _ = torch.sort(recon_error)
    eta = sorted_errors[h-1]  # h-th smallest reconstruction error

    # Compute p_i
    p = torch.clamp((eta - recon_error) / (2 * gamma), min=0)

    # Normalize
    if p.sum() > 0:
        p = p / p.sum()

    print("p updated. Sum(p):", p.sum().item())
    print("Number of non-zero weights:", (p > 0).sum().item())
    print("Sample weights (first 10):", p[:10].cpu().numpy())

print("\nAlgorithm 1 finished successfully.")
X_recon_AR = X @ W @ W.T + b  # store reconstruction for AR

# --- Reconstruction and Evaluation ---
print("\n--- Reconstruction Evaluation ---")

# Reconstruct all samples
X_recon = X @ W @ W.T + b

# Compute per-sample reconstruction errors (mean squared error)
reconstruction_errors = torch.mean((X - X_recon)**2, dim=1)
print("Mean reconstruction error over all samples:", reconstruction_errors.mean().item())
print("Min reconstruction error:", reconstruction_errors.min().item())
print("Max reconstruction error:", reconstruction_errors.max().item())

# --- Visualize original vs reconstructed images ---
num_visualize = 5  # number of images to visualize
img_h, img_w = stack.shape[1], stack.shape[2]

plt.figure(figsize=(12, 4))
for i in range(num_visualize):
    # Original
    plt.subplot(2, num_visualize, i+1)
    plt.imshow(X[i].cpu().reshape(img_h, img_w), cmap='gray')
    plt.title("Original")
    plt.axis('off')

    # Reconstructed
    plt.subplot(2, num_visualize, i+1+num_visualize)
    plt.imshow(X_recon[i].cpu().reshape(img_h, img_w), cmap='gray')
    plt.title("Reconstructed")
    plt.axis('off')

plt.show()

# --- Print weight statistics ---
print("\nWeight statistics after final iteration:")
print("Max weight:", p.max().item())
print("Min weight:", p.min().item())
print("Number of non-zero weights:", (p > 0).sum().item())
print("Sample of weights (first 20):", p[:20].cpu().numpy())

import zipfile
import os

zip_path = '/content/jaffe.zip'
extract_dir = '/content/jaffe'


with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)
print(f"Extracted JAFFE dataset to {extract_dir}")


print("\nContents of the extracted folder:")
for root, dirs, files in os.walk(extract_dir):
    print(f"\nFolder: {root}")
    print(f"Subfolders: {dirs}")
    print(f"Files (first 10 shown): {files[:10]}")

import os
from PIL import Image
import numpy as np

# Path to JAFFE images
jaffe_folder = '/content/jaffe/jaffe'


image_files = [f for f in os.listdir(jaffe_folder) if f.lower().endswith('.tiff')]
image_files.sort()  # optional: sort for consistent order

print(f"Number of images found: {len(image_files)}")
print("First 10 images:", image_files[:10])


images_list = []
for idx, img_file in enumerate(image_files):
    img_path = os.path.join(jaffe_folder, img_file)
    img = Image.open(img_path).convert('L')  # convert to grayscale
    img_array = np.array(img, dtype=np.float32) / 255.0  # normalize to 0-1
    images_list.append(img_array.flatten())  # flatten for PCA/N-RPCA
    if idx < 5:
        print(f"Loaded {img_file}, shape: {img_array.shape}")


X_jaffe = np.stack(images_list)
print("Final JAFFE array shape (n_samples, n_features):", X_jaffe.shape)

import torch
import numpy as np
import matplotlib.pyplot as plt

# --- Device ---
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print("Using device:", device)

# Convert JAFFE array to torch tensor on GPU
X_jaffe_tensor = torch.tensor(X_jaffe, dtype=torch.float32, device=device)
n_samples, n_features = X_jaffe_tensor.shape
img_h, img_w = 256, 256
print("JAFFE tensor shape:", X_jaffe_tensor.shape)

# --- Parameters ---
r = 50        # number of principal components
h = 50        # number of activated error terms (top-h)
sigma = 1.0
gamma = 1.0
max_iter = 10

# --- Step 0: Initialization ---
p = torch.ones(n_samples, device=device) / n_samples
b = torch.mean(X_jaffe_tensor, dim=0)
W = torch.randn(n_features, r, device=device)
U_diag = torch.ones(n_samples, device=device)

print("Initialization complete.")
print(f"p sum: {p.sum().item()}, b shape: {b.shape}, W shape: {W.shape}")

# --- Main Iterative Loop ---
for iteration in range(max_iter):
    print(f"\n=== Iteration {iteration+1} ===")

    # Step 1: Update W using weighted SVD
    print("Updating W...")
    try:
        X_weighted = X_jaffe_tensor.T * torch.sqrt(U_diag)
        _, _, Vt = torch.linalg.svd(X_weighted.T, full_matrices=False)
        W = Vt.T[:, :r]
        print("W updated. Shape:", W.shape)
    except Exception as e:
        print("Error updating W:", e)

    # Step 2: Update b (weighted mean)
    print("Updating b...")
    b = (X_jaffe_tensor.T @ U_diag) / U_diag.sum()
    print("b updated. Sample values (first 5):", b[:5].cpu().numpy())

    # Step 3: Update U_diag (adaptive normalization)
    print("Updating U_diag...")
    avg_local_dist = torch.sum((X_jaffe_tensor - X_jaffe_tensor.mean(dim=0))**2, dim=1) + sigma
    U_diag = n_samples * p * (1 + sigma) / avg_local_dist
    print("U_diag sample values (first 10):", U_diag[:10].cpu().numpy())

    # Step 4: Update weights p (top-h logic)
    print("Updating weights p...")
    recon_error = torch.sum((X_jaffe_tensor - (X_jaffe_tensor @ W @ W.T + b))**2, dim=1)
    sorted_errors, _ = torch.sort(recon_error)
    eta = sorted_errors[h-1]  # top-h smallest
    p = torch.clamp((eta - recon_error) / (2 * gamma), min=0)
    if p.sum() > 0:
        p = p / p.sum()
    print("p sum:", p.sum().item(), "Non-zero weights:", (p > 0).sum().item())
    print("Sample weights (first 10):", p[:10].cpu().numpy())

print("\nN-RPCA on JAFFE finished successfully.")

# --- Reconstruction ---
X_recon = X_jaffe_tensor @ W @ W.T + b
reconstruction_errors = torch.mean((X_jaffe_tensor - X_recon)**2, dim=1)
print("\nReconstruction error over samples:")
print("Mean:", reconstruction_errors.mean().item())
print("Min:", reconstruction_errors.min().item())
print("Max:", reconstruction_errors.max().item())

# --- Visualization: original vs reconstructed ---
num_visualize = 5
plt.figure(figsize=(12, 4))
for i in range(num_visualize):
    # Original
    plt.subplot(2, num_visualize, i+1)
    plt.imshow(X_jaffe_tensor[i].cpu().reshape(img_h, img_w), cmap='gray')
    plt.title("Original")
    plt.axis('off')

    # Reconstructed
    plt.subplot(2, num_visualize, i+1+num_visualize)
    plt.imshow(X_recon[i].cpu().reshape(img_h, img_w), cmap='gray')
    plt.title("Reconstructed")
    plt.axis('off')

plt.show()

# --- Print final weight statistics ---
print("\nFinal weight statistics:")
print("Max weight:", p.max().item())
print("Min weight:", p.min().item())
print("Number of non-zero weights:", (p > 0).sum().item())
print("Sample of first 20 weights:", p[:20].cpu().numpy())

X_recon_JAFFE = X_jaffe_tensor @ W @ W.T + b  # store reconstruction for JAFFE

# Visualize AR dataset (128x128)
num_visualize = 5
plt.figure(figsize=(12, 4))
for i in range(num_visualize):
    plt.subplot(2, num_visualize, i+1)
    plt.imshow(X[i].cpu().reshape(128,128), cmap='gray')
    plt.title("AR Original")
    plt.axis('off')

    plt.subplot(2, num_visualize, i+1+num_visualize)
    plt.imshow(X_recon_AR[i].cpu().reshape(128,128), cmap='gray')
    plt.title("AR Reconstructed")
    plt.axis('off')
plt.show()

# Visualize JAFFE dataset (256x256)
plt.figure(figsize=(12, 4))
for i in range(num_visualize):
    plt.subplot(2, num_visualize, i+1)
    plt.imshow(X_jaffe_tensor[i].cpu().reshape(256,256), cmap='gray')
    plt.title("JAFFE Original")
    plt.axis('off')

    plt.subplot(2, num_visualize, i+1+num_visualize)
    plt.imshow(X_recon_JAFFE[i].cpu().reshape(256,256), cmap='gray')
    plt.title("JAFFE Reconstructed")
    plt.axis('off')
plt.show()